#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Cheesebaron.ParallaxScrollView.Resource", IsApplication=false)]

namespace Cheesebaron.ParallaxScrollView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int parallaxOffset = 2130771968;
			
			private Attribute()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] parallaxscrollview = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public static int parallaxscrollview_parallaxOffset = 0;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
