#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
			Cheesebaron.ParallaxScrollView.Resource.Attribute.parallaxOffset = Sample.Resource.Attribute.parallaxOffset;
			Cheesebaron.ParallaxScrollView.Resource.Styleable.parallaxscrollview = Sample.Resource.Styleable.parallaxscrollview;
			Cheesebaron.ParallaxScrollView.Resource.Styleable.parallaxscrollview_parallaxOffset = Sample.Resource.Styleable.parallaxscrollview_parallaxOffset;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int parallaxOffset = 2130771968;
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int spacing = 2130968576;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int factor_text = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int minus = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int plus = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int scroll_view = 2131165184;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_demo = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello_world = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int menu_settings = 2131034114;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] parallaxscrollview = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int parallaxscrollview_parallaxOffset = 0;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
